force-app/main/default/objects/GameForceLog__c/GameForceLog__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>GameForce Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GameForce Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GameForceLog__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Related User Id (if applicable)</description>
    <label>User Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Related Achievement Id (if applicable)</description>
    <label>Achievement Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GameForceLogger.cls
public with sharing class GameForceLogger {
	
	List<GameForceLog__c> logs = new List<GameForceLog__c>();

	public GameForceLogger () {

	}

	public void addLog(String log, String userId, String achievementId) {
		GameForceLog__c gameForceLog = new GameForceLog__c();
		gameForceLog.Log__C = log;
		if (!String.isBlank(userId)) {
			gameForceLog.UserId__c = userId;
		}

		if (!String.isBlank(achievementId)) {
			gameForceLog.AchievementId__c = achievementId;
		}

		logs.add(gameForceLog);
	}

	public void commitChanges() {
		if (logs.isEmpty()) {
			return;
		}

		Database.insert(logs);
	}

	public static void saveSingleLog(String log, String userId, String achievementId) {
		GameForceLogger logger = new GameForceLogger();
		logger.addLog(log, userId, achievementId);
		logger.commitChanges();
	}
}