force-app/main/default/objects/GameForceLog__c/GameForceLog__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>GameForce Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GameForce Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GameForceLog__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Related User Id (if applicable)</description>
    <label>User Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Related Achievement Id (if applicable)</description>
    <label>Achievement Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GameForceLoggerTest.cls
@IsTest(isParallel=true)
public with sharing class GameForceLoggerTest {
	
	@IsTest
	private static void saveNewLog_logsAddedAndCommited_logsSaved(){
		// Given
		String userId = 'userId';
		String achievementId = 'achievementId';
		String log = 'LOG';

		// When
		Test.startTest();
		GameForceLogger logger = new GameForceLogger();
		logger.addLog(log, userId, achievementId);
		logger.commitChanges();
		Test.stopTest();

		// Then
		List<GameForceLog__c> logs = [SELECT Id, Log__c, UserId__c, AchievementId__c FROM GameForceLog__c];
		System.assertEquals(1, logs.size(), 'Single log is expected to be created');
		System.assertEquals(log, logs[0].Log__c, 'Log value is expected to be saved in Log__c field');
		System.assertEquals(userId, logs[0].UserId__c, 'User Id value is expected to be saved in UserId__c field');
		System.assertEquals(achievementId, logs[0].AchievementId__c, 'Achievement Id value is expected to be saved in AchievementId__c field');
	}

	@IsTest
	private static void saveNewLog_noLogsAddedAndCommited_nothingWasSaved(){
		// Given

		// When
		Test.startTest();
		GameForceLogger logger = new GameForceLogger();
		logger.commitChanges();
		Test.stopTest();

		// Then
		List<GameForceLog__c> logs = [SELECT Id, Log__c, UserId__c, AchievementId__c FROM GameForceLog__c];
		System.assertEquals(0, logs.size(), 'No logs are expected to be created');
	}

	@IsTest
	private static void saveSingleLog_noIssues_logsSaved(){
		// Given
		String userId = 'userId';
		String achievementId = 'achievementId';
		String log = 'LOG';

		// When
		Test.startTest();
		GameForceLogger.saveSingleLog(log, userId, achievementId);
		Test.stopTest();

		// Then
		List<GameForceLog__c> logs = [SELECT Id, Log__c, UserId__c, AchievementId__c FROM GameForceLog__c];
		System.assertEquals(1, logs.size(), 'Single log is expected to be created');
		System.assertEquals(log, logs[0].Log__c, 'Log value is expected to be saved in Log__c field');
		System.assertEquals(userId, logs[0].UserId__c, 'User Id value is expected to be saved in UserId__c field');
		System.assertEquals(achievementId, logs[0].AchievementId__c, 'Achievement Id value is expected to be saved in AchievementId__c field');
	}
}