force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UserStatTriggerHelper.cls
public with sharing class UserStatTriggerHelper {

	public static Map<Id, UserStat__c> getStatsWithUpdatedProgress(Map<Id, sObject> newMap, Map<id, sObject> oldMap) {
		if (newMap == null || newMap.isEmpty()) {
			return new Map<Id, UserStat__c>();
		}
		
		if (oldMap == null || oldMap.isEmpty()) {
			return (Map<Id, UserStat__c>) newMap;
		}
		
		List<UserStat__c> changedStats = new List<UserStat__c>();
		for (Id statId : newMap.keySet()) {
			UserStat__c statNew = (UserStat__c) newMap.get(statId);
			UserStat__c statOld = (UserStat__c) oldMap.get(statId);
			if (statOld != null && 
				statNew != null && 
				statNew.CurrentProgress__c != statOld.CurrentProgress__c) {
				changedStats.add(statNew);
			}
		}
		return new Map<Id, UserStat__c> (changedStats);
	}

}