force-app/main/default/objects/SeasonsConfiguration__c/fields/SeasonScheduledJobId__c.field-meta.xml
<CustomField>
    <fullName>SeasonScheduledJobId__c</fullName>
    <description>Id of the job scheduled for the end of the season</description>
    <label>Season Scheduled JobId</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NextSeasonSchedulable.cls
public with sharing class NextSeasonSchedulable implements Schedulable{
	@TestVisible
	private static Boolean throwException = false;

	public void execute(SchedulableContext sc) {
		try {
			if (throwException) {
				throw new TestDataFactory.TestException();
			}

			SeasonsConfiguration__c config = SeasonsConfiguration__c.getOrgDefaults();
			if (config.IsActive__c) {
				Season__c currentSeason = SeasonSelector.getInstance().getLatestSeason();
				config.SeasonScheduledJobId__c = Database.executeBatch(new SeasonUserStatsBatch(currentSeason.Id));
				update config;
			}
		} catch (Exception e) {
			Logger.saveSingleLog('Unable to execute next Season creation. NextSeasonSchedulable has failed: ' + e.getMessage() + '. ' + e.getStackTraceString());
		}
	}
}