force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserMeasurement__c/UserMeasurement__c.object-meta.xml
<CustomObject>
    <label>User Measurement</label>
    <nameField>
        <displayFormat>UM{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserMeasurement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>User Measurements</relationshipLabel>
    <relationshipName>UserMeasurements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserMeasurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserMeasurementIncrement__e/UserMeasurementIncrement__e.object-meta.xml
<CustomObject>
    <label>UserMeasurement Increment</label>
    <pluralLabel>UserMeasurement Increments</pluralLabel>
</CustomObject>

force-app/main/default/objects/UserMeasurementIncrement__e/fields/Increment__c.field-meta.xml
<CustomField>
    <fullName>Increment__c</fullName>
    <label>Increment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserMeasurementIncrement__e/fields/MeasurementId__c.field-meta.xml
<CustomField>
    <fullName>MeasurementId__c</fullName>
    <label>Measurement Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserMeasurementIncrement__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserMeasurementIncrTriggerHandlerTest.cls
@IsTest(isParallel=true)
private class UserMeasurementIncrTriggerHandlerTest{
	
	@IsTest
	private static void processEvents_singleEventStatsDoesntExist_userStatCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('measurement');
		UserMeasurementIncrement__e event = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurement.Id, Increment__c = 1);

		// When
		Test.startTest();
		UserMeasurementIncrementTriggerHandler handler = new UserMeasurementIncrementTriggerHandler(new List<UserMeasurementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<UserMeasurement__c> measurements = [SELECT Id, Value__c FROM UserMeasurement__c WHERE User__c = :userId AND Measurement__c = :measurement.Id];
		system.assertEquals(1, measurements.size(), 'Single stat is expected to be created');
		system.assertEquals(1, measurements[0].Value__c, 'Value__c value should be increased for the sum of the increments from the event');
	}

	@IsTest
	private static void processEvents_multipleEventsWithSameIds_userStatCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('measurement');
		UserMeasurementIncrement__e event1 = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurement.Id, Increment__c = 1);
		UserMeasurementIncrement__e event2 = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurement.Id, Increment__c = 2);

		// When
		Test.startTest();
		UserMeasurementIncrementTriggerHandler handler = new UserMeasurementIncrementTriggerHandler(new List<UserMeasurementIncrement__e> { event1, event2 });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<UserMeasurement__c> measurements = [SELECT Id, Value__c FROM UserMeasurement__c WHERE User__c = :userId AND Measurement__c = :measurement.Id];
		system.assertEquals(1, measurements.size(), 'Single stat is expected to be created');
		system.assertEquals(3, measurements[0].Value__c, 'Value__c value should be increased for the sum of the increments from the event');
	}

	@IsTest
	private static void processEvents_existingUserStat_userStatUpdated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('measurement');
		UserMeasurement__c stat = TestDataFactory.createUserMeasurement(userId, measurement.Id, 10);

		UserMeasurementIncrement__e event = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurement.Id, Increment__c = 1);

		// When
		Test.startTest();
		UserMeasurementIncrementTriggerHandler handler = new UserMeasurementIncrementTriggerHandler(new List<UserMeasurementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<UserMeasurement__c> measurements = [SELECT Id, Value__c FROM UserMeasurement__c WHERE User__c = :userId AND Measurement__c = :measurement.Id];
		system.assertEquals(1, measurements.size(), 'Single stat is expected to be created');
		system.assertEquals(stat.Id, measurements[0].Id, 'Existing UserMeasurement__c is expected to be updated');
		system.assertEquals(11, measurements[0].Value__c, 'Value__c value should be increased for the sum of the increments from the event');
	}

	@IsTest
	private static void processEvents_nonExistingMeasurementId_logCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('measurement');
		String measurementId = measurement.Id;
		delete measurement;
		UserMeasurementIncrement__e event = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurementId, Increment__c = 1);

		// When
		Test.startTest();
		UserMeasurementIncrementTriggerHandler handler = new UserMeasurementIncrementTriggerHandler(new List<UserMeasurementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<Log__c> logs = [SELECT Id, Log__c FROM Log__c];
		System.assertEquals(1, logs.size(), 'Error Log is expected to be created');
	}

	@IsTest
	private static void processEvents_incrementIsNull_logCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('measurement');
		UserMeasurementIncrement__e event = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurement.Id, Increment__c = 0);

		// When
		Test.startTest();
		UserMeasurementIncrementTriggerHandler handler = new UserMeasurementIncrementTriggerHandler(new List<UserMeasurementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<Log__c> logs = [SELECT Id, Log__c FROM Log__c];
		System.assertEquals(1, logs.size(), 'Error Log is expected to be created');
	}

	@IsTest
	private static void onAfterInsert_eventGetsPublished_userStatCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('measurement');

		// When
		Test.startTest();
		UserMeasurementIncrement__e event = new UserMeasurementIncrement__e(UserId__c = userId, MeasurementId__c = measurement.Id, Increment__c = 1);
		EventBus.publish(new List<UserMeasurementIncrement__e> { event });
		Test.stopTest();

		// Then
		List<UserMeasurement__c> measurements = [SELECT Id, Value__c FROM UserMeasurement__c WHERE User__c = :userId AND Measurement__c = :measurement.Id];
		system.assertEquals(1, measurements.size(), 'Single stat is expected to be created');
		system.assertEquals(1, measurements[0].Value__c, 'Value__c value should be increased for the sum of the increments from the event');
	}

}