force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public with sharing class Logger {
	
	List<Log__c> logs = new List<Log__c>();

	public Logger () { }

	public void addLog(String log) {
		Log__c scoreHubLog = new Log__c();
		if (String.isBlank(log)) {
			return;
		}

		scoreHubLog.ErrorMessage__c = log;
		logs.add(scoreHubLog);
	}

	public void commitChanges() {
		if (logs.isEmpty()) {
			return;
		}

		if (Log__c.SObjectType.getDescribe().isAccessible() && 
			Log__c.SObjectType.getDescribe().isCreateable() &&
			Schema.SObjectType.Log__c.fields.ErrorMessage__c.isAccessible() && 
			Schema.SObjectType.Log__c.fields.ErrorMessage__c.isCreateable()) {
			Database.insert(logs);
		}
	}

	public static void saveSingleLog(String log) {
		if (!System.isFuture() && !System.isBatch() && !System.isQueueable() && !System.isScheduled()) {
			saveSingleLogAsync(log);
		} else {
			saveSingleLogSync(log);
		}
	}

	@future
	private static void saveSingleLogAsync(String log) {
		saveSingleLogSync(log);
	}

	private static void saveSingleLogSync(String log) {
		Logger logger = new Logger();
		logger.addLog(log);
		logger.commitChanges();
	}

}