force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Related Achievement Id (if applicable)</description>
    <label>Achievement Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LoggerTest.cls
@IsTest
public with sharing class LoggerTest {
	
	@IsTest
	private static void saveNewLog_logsAddedAndCommited_logsSaved(){
		// Given
		String log = 'LOG';
		User testUsr = TestDataFactory.createUser(UserInfo.getProfileId(), 'Test');
		TestDataFactory.assignPermissionSet(testUsr.Id, 'ScoreHubModifyLogs');

		system.runAs(testUsr) {
			// When
			Test.startTest();
			Logger logger = new Logger();
			logger.addLog(log);
			logger.commitChanges();
			Test.stopTest();

			// Then
			List<Log__c> logs = [SELECT Id, ErrorMessage__c, UserId__c, AchievementId__c FROM Log__c];
			Assert.areEqual(1, logs.size(), 'Single log is expected to be created');
			Assert.areEqual(log, logs[0].ErrorMessage__c, 'Log value is expected to be saved in Log__c field');
		}
	}

	@IsTest
	private static void saveNewLog_noLogsAddedAndCommited_nothingWasSaved(){
		// Given

		// When
		Test.startTest();
		Logger logger = new Logger();
		logger.commitChanges();
		Test.stopTest();

		// Then
		List<Log__c> logs = [SELECT Id, ErrorMessage__c FROM Log__c];
		Assert.areEqual(0, logs.size(), 'No logs are expected to be created');
	}

	@IsTest
	private static void saveNewLog_emptyLogValue_nothingWasSaved(){
		// Given
		String log = '';

		// When
		Test.startTest();
		Logger logger = new Logger();
		logger.addLog(log);
		logger.commitChanges();
		Test.stopTest();

		// Then
		List<Log__c> logs = [SELECT Id, ErrorMessage__c FROM Log__c];
		Assert.areEqual(0, logs.size(), 'No logs are expected to be created');
	}

	@IsTest
	private static void saveSingleLog_noIssues_logsSaved(){
		// Given
		String log = 'LOG';
		User testUsr = TestDataFactory.createUser(UserInfo.getProfileId(), 'Test');
		TestDataFactory.assignPermissionSet(testUsr.Id, 'ScoreHubModifyLogs');

		system.runAs(testUsr) {
			// When
			Test.startTest();
			Logger.saveSingleLog(log);
			Test.stopTest();

			// Then
			List<Log__c> logs = [SELECT Id, ErrorMessage__c FROM Log__c];
			Assert.areEqual(1, logs.size(), 'Single log is expected to be created');
			Assert.areEqual(log, logs[0].ErrorMessage__c, 'Log value is expected to be saved in Log__c field');
		}
	}
}