force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measurement__c/fields/UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UniqueIdentifier__c</fullName>
    <description>Unique name for the measurement</description>
    <label>Unique Identifier</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UserMeasurementIncrement__e/UserMeasurementIncrement__e.object-meta.xml
<CustomObject>
    <label>UserMeasurement Increment</label>
    <pluralLabel>UserMeasurement Increments</pluralLabel>
</CustomObject>

force-app/main/default/objects/UserMeasurementIncrement__e/fields/Increment__c.field-meta.xml
<CustomField>
    <fullName>Increment__c</fullName>
    <label>Increment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserMeasurementIncrement__e/fields/MeasurementId__c.field-meta.xml
<CustomField>
    <fullName>MeasurementId__c</fullName>
    <label>Measurement Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserMeasurementIncrement__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BaseGameForceTriggerHandler.cls
public virtual class BaseGameForceTriggerHandler {
	Map<String, Id> measurementIdsByUniqueIds = new Map<String, Id>();

	public BaseGameForceTriggerHandler () {
		initMeasurementsIds();
	}
	
	private void initMeasurementsIds() {
		for (String measurementUniqueId : Constants.MEASUREMENT_UNIQUE_IDS) {
			measurementIdsByUniqueIds.put(measurementUniqueId, null);
		}

		List<Measurement__c> measurements = (List<Measurement__c>) MeasurementSelector.getInstance().getByFieldValue('UniqueIdentifier__c', 'IN', Constants.MEASUREMENT_UNIQUE_IDS);
		for (Measurement__c measurement : measurements) {
			measurementIdsByUniqueIds.put(measurement.UniqueIdentifier__c, measurement.Id);
		}
	}

	public void fireEvents(List<SObject> objects, String userFieldApiName, String measurementUniqueId) {
		List<UserMeasurementIncrement__e> events = new List<UserMeasurementIncrement__e>();
		Id measurementId = measurementIdsByUniqueIds.get(measurementUniqueId);
		if (measurementId == null) {
			return;
		}

		Map<Id, Decimal> incrementsByUserId = new Map<Id, Decimal>();

		for (SObject obj : objects) {
			Id userId = (Id) obj.get(userFieldApiName);
			if (incrementsByUserId.containsKey(userId)) {
				Decimal value = incrementsByUserId.get(userId);
				incrementsByUserId.put(userId, value + 1);
			} else {
				incrementsByUserId.put(userId, 1);
			}
		}

		if (incrementsByUserId.isEmpty()) {
			return;
		}

		for (Id key : incrementsByUserId.keySet()) {
			UserMeasurementIncrement__e event = new UserMeasurementIncrement__e();
			event.UserId__c = key;
			event.MeasurementId__c = measurementId;
			event.Increment__c = incrementsByUserId.get(key);
			events.add(event);
		}

		if (!events.isEmpty()) {
			EventBus.publish(events);
		}
	}
}