force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonUserMeasurement__c/SeasonUserMeasurement__c.object-meta.xml
<CustomObject>
    <label>Season User Measurement</label>
    <nameField>
        <displayFormat>UM{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Season User Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonUserMeasurement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Season User Measurements</relationshipLabel>
    <relationshipName>SeasonUserMeasurements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeasonUserMeasurement__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Season User Measurements</relationshipLabel>
    <relationshipName>SeasonUserMeasurements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeasonUserMeasurement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SeasonUserMeasurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/UserMeasurement__c.object-meta.xml
<CustomObject>
    <label>User Measurement</label>
    <nameField>
        <displayFormat>UM{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserMeasurement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>User Measurements</relationshipLabel>
    <relationshipName>UserMeasurements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserMeasurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SeasonUserMeasurementsBatch.cls
public with sharing class SeasonUserMeasurementsBatch implements Database.Batchable<sObject>, Database.Stateful {
	public Id currentSeasonId;

	public SeasonUserMeasurementsBatch(Id seasonId) {
		SeasonsConfiguration__c config = SeasonsConfiguration__c.getOrgDefaults();
		if (config.IsActive__c != true) {
			throw new SeasonUserMeasurementsBatchException('SeasonUserMeasurementsBatch execution was stopped - Seasons feature is not active');
		}

		if (seasonId == null || seasonId.getSobjectType() != Season__c.getSobjectType()) {
			throw new SeasonUserMeasurementsBatchException('Unable to execute SeasonUserMeasurementsBatch. Provided season id is either null or is not of Season__c type'); 
		}

		currentSeasonId = seasonId;
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		String queryString = 'SELECT Id, Measurement__c, User__c, Value__c FROM UserMeasurement__c';
		return Database.getQueryLocator(queryString);
	}

	public void execute(Database.BatchableContext bc, List<sObject> scope) {
		List<SeasonUserMeasurement__c> seasonUserMeasurementsToCreate = new List<SeasonUserMeasurement__c>();

		for (UserMeasurement__c userMeasurement : (List<UserMeasurement__c>)scope) {
			SeasonUserMeasurement__c seasonUserMeasurement = new SeasonUserMeasurement__c();
			seasonUserMeasurement.Season__c = currentSeasonId;
			seasonUserMeasurement.User__c = userMeasurement.User__c;
			seasonUserMeasurement.Measurement__c = userMeasurement.Measurement__c;
			seasonUserMeasurement.Value__c = userMeasurement.Value__c;

			seasonUserMeasurementsToCreate.add(seasonUserMeasurement);
		}
		insert seasonUserMeasurementsToCreate;
		delete scope;
	}

	public void finish(Database.BatchableContext bc) {
		AsyncApexJob asyncJobInfo = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
				FROM AsyncApexJob WHERE Id = :bc.getJobId()];

		if (asyncJobInfo.NumberOfErrors != 0 || asyncJobInfo.Status == 'Failed') {
			Logger.saveSingleLog('SeasonUserMeasurementsBatch with Id: ' + asyncJobInfo.Id +' has failed. New Season is not going to be created.');
		} else {
			SeasonsDataHelper helper = new SeasonsDataHelper();
			helper.createNewSeason(this.currentSeasonId);
		}
	}

	public class SeasonUserMeasurementsBatchException extends Exception {}
}