force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonUserMeasurement__c/SeasonUserMeasurement__c.object-meta.xml
<CustomObject>
    <label>Season User Measurement</label>
    <nameField>
        <displayFormat>UM{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Season User Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonUserMeasurement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Season User Measurements</relationshipLabel>
    <relationshipName>SeasonUserMeasurements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeasonUserMeasurement__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>Season User Measurements</relationshipLabel>
    <relationshipName>SeasonUserMeasurements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeasonUserMeasurement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SeasonUserMeasurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/UserMeasurement__c.object-meta.xml
<CustomObject>
    <label>User Measurement</label>
    <nameField>
        <displayFormat>UM{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserMeasurement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>User Measurements</relationshipLabel>
    <relationshipName>UserMeasurements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserMeasurements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SeasonUserMeasurementsBatchTest.cls
@IsTest(isParallel=false)
private class SeasonUserMeasurementsBatchTest {

	@TestSetup
	private static void setup() {
		SeasonsConfiguration__c config = new SeasonsConfiguration__c();
		config.IsActive__c = true;
		config.Cadence__c = 'month';
		config.StartDate__c = Date.today();
		insert config;
	}
	
	@IsTest
	private static void execute_allDataExists_userMeasurementsStored() {
		// Given 
		User testUser = TestDataFactory.createUser(UserInfo.getProfileId(), 'Test_SidebarApps');
		Season__c currentSeason = TestDataFactory.createSeason(Date.today().addDays(-3), Date.today());

		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		UserMeasurement__c userMeasurement = TestDataFactory.createUserMeasurement(testUser.Id, measurement.Id, 10);

		// When 
		Test.startTest();
		Database.executeBatch(new SeasonUserMeasurementsBatch(currentSeason.Id), 200);
		Test.stopTest();

		// Then
		List<UserMeasurement__c> userMeasurements = [SELECT Id FROM UserMeasurement__c];
		Assert.isTrue(userMeasurements.isEmpty(), 'UserMeasurement__c sObject records are supposed to be cleaned-up');

		List<SeasonUserMeasurement__c> seasonUserMeasurements = [SELECT Id, User__c, Season__c, Measurement__c, Value__c FROM SeasonUserMeasurement__c];
		Assert.areEqual(1, seasonUserMeasurements.size(), 'Each UserMeasurement__c is expected to be migrated');

		SeasonUserMeasurement__c seasonReachedAchievement = seasonUserMeasurements[0];
		Assert.areEqual(currentSeason.Id, seasonReachedAchievement.Season__c, 'User Id is expected to be migrated');
		Assert.areEqual(testUser.Id, seasonReachedAchievement.User__c, 'User Id is expected to be migrated');
		Assert.areEqual(measurement.Id, seasonReachedAchievement.Measurement__c, 'Measurement Id is expected to be migrated');
		Assert.areEqual(10, seasonReachedAchievement.Value__c, 'Value is expected to be migrated');
	}

	@IsTest
	private static void execute_200userMeasurements_200userMeasurementsStored() {
		// Given 
		User testUser = TestDataFactory.createUser(UserInfo.getProfileId(), 'Test_SidebarApps');
		Season__c currentSeason = TestDataFactory.createSeason(Date.today().addDays(-3), Date.today());

		List<Measurement__c> testMeasurements = new List<Measurement__c>();
		for (Integer i = 0; i < 200; i++) {
			testMeasurements.add(TestDataFactory.initMeasurement('Measurement' + String.valueOf(i)));
		}
		insert testMeasurements;
		testMeasurements = [SELECT Id FROM Measurement__c];

		List<UserMeasurement__c> userMeasurements = new List<UserMeasurement__c>();
		for (Measurement__c measurement : testMeasurements) {
			userMeasurements.add(TestDataFactory.initUserMeasurement(testUser.Id, measurement.Id, 10));
		}
		insert userMeasurements;

		// When 
		Test.startTest();
		Database.executeBatch(new SeasonUserMeasurementsBatch(currentSeason.Id), 200);
		Test.stopTest();

		// Then
		userMeasurements = [SELECT Id FROM UserMeasurement__c];
		Assert.isTrue(userMeasurements.isEmpty(), 'UserMeasurement__c sObject records are supposed to be cleaned-up');

		List<SeasonUserMeasurement__c> seasonUserMeasurements = [SELECT Id, User__c FROM SeasonUserMeasurement__c];
		Assert.areEqual(200, seasonUserMeasurements.size(), 'Each UserMeasurement__c is expected to be migrated');
	}

	@IsTest
	private static void execute_seasonIdIsWrong_exceptionIsThrown() {
		// Given 
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');

		// When 
		try { 
			Test.startTest();
			Database.executeBatch(new SeasonUserMeasurementsBatch(measurement.Id), 200);
			Test.stopTest();

		// Then
			Assert.fail('Exception is expected to be thrown');
		} catch (SeasonUserMeasurementsBatch.SeasonUserMeasurementsBatchException e) {
			String msg = 'Unable to execute SeasonUserMeasurementsBatch. Provided season id is either null or is not of Season__c type';
			Assert.areEqual(msg, e.getMessage(), 'SeasonUserMeasurementsBatchException exception is expected');
		} catch (Exception e) {
			Assert.fail('Exception of SeasonUserMeasurementsBatchException is expected');
		}
	}
}