force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of points that user gets, once reaching the achievement. Used to calculate high-score on the leaderboard</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <formula>CASESAFEID( User__r.Id ) + &apos;-&apos; + CASESAFEID( Achievement__r.Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Achievement__r.Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReachedAchievementSelector.cls
public with sharing class ReachedAchievementSelector extends BaseSelector {
	
	public static ReachedAchievementSelector getInstance() {
		return new ReachedAchievementSelector();
	}

	public override SObjectType sObjectType() {
		return ReachedAchievement__c.getSobjectType();
	}

	public override Set<SObjectField> queryFields() {
		return new Set<SObjectField> { ReachedAchievement__c.Id, ReachedAchievement__c.Key__c, ReachedAchievement__c.User__c, ReachedAchievement__c.Achievement__c, ReachedAchievement__c.Score__c, ReachedAchievement__c.CreatedDate };
	}
}