force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AchievementIncrement__e/AchievementIncrement__e.object-meta.xml
<CustomObject>
    <label>Achievement Increment</label>
    <pluralLabel>Achievement Increments</pluralLabel>
</CustomObject>

force-app/main/default/objects/AchievementIncrement__e/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement custom metadata type record name</description>
    <label>Achievement</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AchievementIncrement__e/fields/Increment__c.field-meta.xml
<CustomField>
    <fullName>Increment__c</fullName>
    <description>Value that is going to be added to User Stat - Progress field</description>
    <label>Increment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AchievementIncrement__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>User Id</description>
    <label>UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AchievementIncrementTriggerHandler.cls
public with sharing class AchievementIncrementTriggerHandler {
	GameForceLogger logger = new GameForceLogger();
	List<AchievementIncrement__e> eventsToProcess = new List<AchievementIncrement__e>();
	Map<Id, User> existingUsersMap = new Map<Id, User>();
	Map<Id, Achievement__c> existingAchievementsMap = new Map<Id, Achievement__c>();
	Map<String, UserStat__c> existingUserStatMap = new Map<String, UserStat__c>();
	Map<String, UserStat__c> statsToUpsert = new Map<String, UserStat__c>();

	public AchievementIncrementTriggerHandler(List<AchievementIncrement__e> events) {
		eventsToProcess = events;
		initExistingSObjectMaps(events);
	}

	private void initExistingSObjectMaps(List<AchievementIncrement__e> events) {
		Set<Id> userIdsFromEvents = new Set<Id>();
		Set<Id> achievementIdsFromEvents = new Set<Id>();
		Map<Id, Id> achievementIdByUserIdsMap = new Map<Id, Id>();
		for (AchievementIncrement__e event : events) {
			userIdsFromEvents.add(event.UserId__c);
			achievementIdsFromEvents.add(event.Achievement__c);
			achievementIdByUserIdsMap.put(event.UserId__c, event.Achievement__c);
		}

		existingUsersMap = new Map<Id, User> (UserSelector.getByIds(userIdsFromEvents));
		existingAchievementsMap = new Map<Id, Achievement__c> (AchievementSelector.getByIds(achievementIdsFromEvents));
		existingUserStatMap = UserStatSelector.getByKeys(achievementIdByUserIdsMap);
	}

	public void processEvents() {
		try {
			for (AchievementIncrement__e event : eventsToProcess) {
				if (!this.validateEvent(event)) {
					continue;
				}

				String upsertMapKey = event.UserId__c + '-' + event.Achievement__c;
				if (statsToUpsert.containsKey(upsertMapKey)) {
					statsToUpsert.get(upsertMapKey).CurrentProgress__c += event.Increment__c;
				} else if (existingUserStatMap.containsKey(upsertMapKey)) {
					statsToUpsert.put(upsertMapKey, existingUserStatMap.get(upsertMapKey));
					statsToUpsert.get(upsertMapKey).CurrentProgress__c += event.Increment__c;
				} else {
					statsToUpsert.put(upsertMapKey, new UserStat__c(Achievement__c = event.Achievement__c, UserId__c = event.UserId__c, CurrentProgress__c = event.Increment__c));
				}
			}

			this.commitChanges();
		} catch (Exception e) {
			logger.addLog('Unexpected exception was caught: ' + e.getMessage(), null, null);
		} finally {
			logger.commitChanges();
		}
	}

	private Boolean validateEvent(AchievementIncrement__e event) {
		User user = existingUsersMap.get(event.UserId__c);
		if (user == null) {
			logger.addLog('User with Id: ' + event.UserId__c + ' haven\'t been found in a system.', event.UserId__c, event.Achievement__c);
			return false;
		}

		Achievement__c achievement = existingAchievementsMap.get(event.Achievement__c);
		if (achievement == null) {
			logger.addLog('Achievement with Id: ' + event.Achievement__c + ' haven\'t been found in a system.', event.UserId__c, event.Achievement__c);
			return false;
		}

		if (event.Increment__c == null || event.Increment__c == 0) {
			logger.addLog('User Stat wasn\'t updated since Increment value is missing', event.UserId__c, event.Achievement__c);
			return false;
		}

		return true;
	}

	private void commitChanges() {
		if (statsToUpsert.isEmpty()) {
			return;
		}

		// Use proper Database class operations and throw events 
		List<Database.UpsertResult> upsertResults = Database.upsert(statsToUpsert.values(), false);
		// Create an error log for each faild upsert record in Issue #26
		for (Database.UpsertResult upsertResult : upsertResults) {
			if (!upsertResult.isSuccess()) {
				for (Database.Error error : upsertResult.getErrors()) {
					logger.addLog('Unable to update User Stat: ' + error.getMessage() , null, null);
				}
			}
		}
	}

	public static void onAfterInsert(List<AchievementIncrement__e> events) {
		try {
			AchievementIncrementTriggerHandler handler = new AchievementIncrementTriggerHandler(events);
			handler.processEvents();
		} catch (Exception e) {
			GameForceLogger.saveSingleLog('AchievementIncrement__e onAfterInsert trigger issue: ' + e.getMessage(), null, null);
		}
	}
}