force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AchievementReached__e/AchievementReached__e.object-meta.xml
<CustomObject>
    <description>Fired when user has reached the achievement</description>
    <label>Achievement Reached</label>
    <pluralLabel>Achievements Reached</pluralLabel>
</CustomObject>

force-app/main/default/objects/AchievementReached__e/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Id of a specific Achievement</description>
    <label>Achievement Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AchievementReached__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of a user who has gotten an achievement</description>
    <label>User Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/Reached__c.field-meta.xml
<CustomField>
    <fullName>Reached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true, in case achievement was reached by user</description>
    <label>Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AchievementReachedEventsManager.cls
public with sharing class AchievementReachedEventsManager {

	Map<Id, UserStat__c> userStatsByIdMap = new Map<Id, UserStat__c>();
	Map<Id, Achievement__c> achievementByIdMap = new Map<Id, Achievement__c>();

	public AchievementReachedEventsManager(Map<Id, UserStat__c> userStatsByIdMap) {
		this.userStatsByIdMap = userStatsByIdMap;
		this.populateAchievementsMap();
	}

	public List<Database.SaveResult> fireEvents() {
		List<Database.SaveResult> results;
		if (validate()) {
			List<AchievementReached__e> achievementReachedEvents = new List<AchievementReached__e>();
			for (UserStat__c stat : userStatsByIdMap.values()) {
				Achievement__c achievement = achievementByIdMap.get(stat.Achievement__c);
				if (achievement != null && 
					stat.CurrentProgress__c >= achievement.Goal__c && 
					!stat.Reached__c) {
					AchievementReached__e event = new AchievementReached__e();
					event.UserId__c = stat.UserId__c;
					event.AchievementId__c = stat.Achievement__c;
					achievementReachedEvents.add(event);
				}
			}

			if (!achievementReachedEvents.isEmpty()) {
				results = EventBus.publish(achievementReachedEvents);
			}
		}
		return results;
	}

	private void populateAchievementsMap() {
		Set<Id> achievementIds = new Set<Id>();
		for (UserStat__c userStat : userStatsByIdMap.values()) {
			achievementIds.add(userStat.Achievement__c);
		}
		achievementByIdMap = new Map<Id, Achievement__c>(AchievementSelector.getByIds(achievementIds));
	}
	
	private Boolean validate() {
		Boolean result = true;

		if (userStatsByIdMap.isEmpty() || achievementByIdMap.isEmpty()) {
			result = false;
		}

		return result;
	}
}