force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description for the achievement</description>
    <inlineHelpText>Short description used by admin users to better identify list of achievements</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of points that user gets, once reaching the achievement. Used to calculate high-score on the leaderboard</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UIDescription__c.field-meta.xml
<CustomField>
    <fullName>UIDescription__c</fullName>
    <description>Achievement description that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UITitle__c.field-meta.xml
<CustomField>
    <fullName>UITitle__c</fullName>
    <description>Achievement title that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measurement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measurement__c/fields/UniqueIdentifier__c.field-meta.xml
<CustomField>
    <fullName>UniqueIdentifier__c</fullName>
    <description>Unique name for the measurement</description>
    <label>Unique Identifier</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ConfigurationTabControllerTest.cls
@IsTest(isParallel=false)
private class ConfigurationTabControllerTest {

	@IsTest
	private static void restoreDefaultAchievements_NoIssues_AchievementsRestored() {
		System.runAs(TestDataFactory.createUserTestAdmin()) {
			// Given
			Measurement__c defaultMeasurement = new Measurement__c();
			defaultMeasurement.UniqueIdentifier__c = Constants.CHATTER_POSTS_COUNTER_ID;
			defaultMeasurement.Description__c = 'Description was changed by admin';
			
			insert new List<Measurement__c>{ defaultMeasurement };

			Achievement__c achievement = new Achievement__c();
			achievement.Name = Constants.CHATTER_POSTS_1_NAME;
			achievement.Measurement__c = defaultMeasurement.Id;
			achievement.UITitle__c = 'Enthusiast Changed';
			achievement.UIDescription__c = 'Create 121 Chatter posts';
			achievement.Description__c = 'Standard Achievement, that was changed';
			achievement.Goal__c = 121;
			achievement.Score__c = 1000;
			insert achievement;

			system.debug(achievement);

			// When
			Test.startTest();
			ConfigurationTabController.restoreDefaultAchievements();
			Test.stopTest();

			// Then
			Measurement__c defaultMeasurementResult = [SELECT Id, UniqueIdentifier__c, Description__c FROM Measurement__c WHERE Id = :defaultMeasurement.Id LIMIT 1];
			Achievement__c achievementResult = [SELECT Id, Measurement__c, UITitle__c, UIDescription__c, Description__c, Goal__c, Score__c FROM Achievement__c WHERE Id = :achievement.Id LIMIT 1];

			Assert.areEqual(Constants.CHATTER_POSTS_COUNTER_ID, defaultMeasurementResult.UniqueIdentifier__c, 'Default measurement is expected to be restored');
			Assert.areEqual('Number of Chatter posts that were posted by user', defaultMeasurementResult.Description__c, 'Default measurement is expected to be restored');

			Assert.areEqual('Enthusiast', achievementResult.UITitle__c, 'Default achievement is expected to be restored');
			Assert.areEqual('Create 10 Chatter posts', achievementResult.UIDescription__c, 'Default achievement is expected to be restored');
			Assert.areEqual('Standard Achievement, that can be reached by creating 10 posts in Chatter', achievementResult.Description__c, 'Default achievement is expected to be restored');
			Assert.areEqual(10, achievementResult.Goal__c, 'Default achievement is expected to be restored');
			Assert.areEqual(10, achievementResult.Score__c, 'Default achievement is expected to be restored');
		}
	}

	@IsTest
	private static void restoreDefaultAchievements_ExceptionThrown_ExceptionHandled() {
		// Given
		System.runAs(TestDataFactory.createUserTestAdmin()) {
			ConfigurationTabController.throwException = true;

			// When
			try {
				Test.startTest();
				Map<String, Object> result = ConfigurationTabController.restoreDefaultAchievements();
				Test.stopTest();

				// Then
			} catch (Exception e) {
				Assert.fail('Exception is expected to be handled safely');
			}
		}
	}
}