force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserMeasurement__c/UserMeasurement__c.object-meta.xml
<CustomObject>
    <label>User Measurement</label>
    <nameField>
        <displayFormat>UM{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Measurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserMeasurement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>User Measurements</relationshipLabel>
    <relationshipName>UserMeasurements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserMeasurement__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UserMeasurementTriggerHandlerTest.cls
@IsTest(isParallel=true)
private class UserMeasurementTriggerHandlerTest {
	@IsTest
	private static void getMeasurementsWithUpdatedProgress_currentProgressIsChanged_recordsReturned() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurment');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		UserMeasurement__c userMeasurementNew1 = TestDataFactory.createUserMeasurement(userId, measurement.Id, 10);
		UserMeasurement__c userMeasurementNew2 = TestDataFactory.createUserMeasurement(userId, measurement.Id, 10);

		UserMeasurement__c oldMeasurement1 = new UserMeasurement__c(Id = userMeasurementNew1.Id);
		oldMeasurement1.Value__c = userMeasurementNew1.Value__c + 1;
		UserMeasurement__c oldMeasurement2 = new UserMeasurement__c(Id = userMeasurementNew2.Id);
		oldMeasurement2.Value__c = userMeasurementNew2.Value__c;

		Map<Id, UserMeasurement__c> newMap = new Map<Id, UserMeasurement__c> { userMeasurementNew1.Id => userMeasurementNew1, userMeasurementNew2.Id => userMeasurementNew2 };
		Map<Id, UserMeasurement__c> oldMap = new Map<Id, UserMeasurement__c> { oldMeasurement1.Id => oldMeasurement1, oldMeasurement2.Id => oldMeasurement2 };

		// When
		Test.startTest();
		Map<Id, UserMeasurement__c> result = UserMeasurementTriggerHandler.getMeasurementsWithUpdatedProgress(newMap, oldMap);
		Test.stopTest();

		// Then
		System.assertEquals(1, result.size(), 'Only one UserMeasurement__c record is expected to be returned');
		System.assert(result.containsKey(userMeasurementNew1.Id), 'Changed UserMeasurement__c is expected to be included');
		System.assert(!result.containsKey(userMeasurementNew2.Id), 'Not changed UserMeasurement__c is not expected to be included');

	}

	@IsTest
	private static void getMeasurementsWithUpdatedProgress_oldMapIsEmpty_newMapIsReturned() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurment');
		Achievement__c achievement = TestDataFactory.createAchievement('Test', measurement.Id);
		UserMeasurement__c userMeasurementNew1 = TestDataFactory.createUserMeasurement(userId, measurement.Id, 10);
		UserMeasurement__c userMeasurementNew2 = TestDataFactory.createUserMeasurement(userId, measurement.Id, 10);

		Map<Id, UserMeasurement__c> newMap = new Map<Id, UserMeasurement__c> { userMeasurementNew1.Id => userMeasurementNew1, userMeasurementNew2.Id => userMeasurementNew2 };
		Map<Id, UserMeasurement__c> oldMap = new Map<Id, UserMeasurement__c> ();

		// When
		Test.startTest();
		Map<Id, UserMeasurement__c> result = UserMeasurementTriggerHandler.getMeasurementsWithUpdatedProgress(newMap, oldMap);
		Test.stopTest();

		// Then
		System.assertEquals(2, result.size(), 'Only one UserMeasurement__c record is expected to be returned');
		System.assert(result.containsKey(userMeasurementNew1.Id), 'Since there are no old UserMeasurement__c records to compare, all "new" records are treated as "changed"');
		System.assert(result.containsKey(userMeasurementNew2.Id), 'Since there are no old UserMeasurement__c records to compare, all "new" records are treated as "changed"');
	}

	@IsTest
	private static void getMeasurementsWithUpdatedProgress_newMapIsEmpty_emptyMapIsReturned() {
		// Given
		Map<Id, UserMeasurement__c> newMap = new Map<Id, UserMeasurement__c> ();
		Map<Id, UserMeasurement__c> oldMap = new Map<Id, UserMeasurement__c> ();

		// When
		Test.startTest();
		Map<Id, UserMeasurement__c> result = UserMeasurementTriggerHandler.getMeasurementsWithUpdatedProgress(newMap, oldMap);
		Test.stopTest();

		// Then
		System.assertNotEquals(null, result, 'Empty map is expected but not null');
		System.assertEquals(0, result.size(), 'Empty map is expected but not null');
	}
}