force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AchievementReached__e/AchievementReached__e.object-meta.xml
<CustomObject>
    <description>Fired when user has reached the achievement</description>
    <label>Achievement Reached</label>
    <pluralLabel>Achievements Reached</pluralLabel>
</CustomObject>

force-app/main/default/objects/AchievementReached__e/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Id of a specific Achievement</description>
    <label>Achievement Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AchievementReached__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Id of a user who has gotten an achievement</description>
    <label>User Id</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Related Achievement Id (if applicable)</description>
    <label>Achievement Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <formula>CASESAFEID( User__r.Id ) + &apos;-&apos; + CASESAFEID( Achievement__r.Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AchievementReachedTriggerHandlerTest.cls
@IsTest(isParallel=true)
private class AchievementReachedTriggerHandlerTest {
	@IsTest
	private static void processEvents_noExistingReachedAchievements_recordCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		List<AchievementReached__e> events = new List<AchievementReached__e> {
			new AchievementReached__e(UserId__c = userId, AchievementId__c = achievement.Id)
		};

		// When
		Test.startTest();
		AchievementReachedTriggerHandler handler = new AchievementReachedTriggerHandler(events);
		handler.processEvents();
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> result = [SELECT Id, Key__c, User__c, Achievement__c FROM ReachedAchievement__c];
		Assert.isNotNull(result, 'ReachedAchievement__c are expected to be created');
		Assert.areEqual(1, result.size(), 'Single ReachedAchievement__c is expected to be created');
		Assert.areEqual(userId, result[0].User__c, 'User__c filed value is expected to match userId');
		Assert.areEqual(achievement.Id, result[0].Achievement__c, 'User__c filed value is expected to match userId');
	}

	@IsTest
	private static void processEvents_existingReachedAchievement_noRecordCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		ReachedAchievement__c reachedAchievement = TestDataFactory.createReachedAchievement(userId, achievement.Id);
		List<AchievementReached__e> events = new List<AchievementReached__e> {
			new AchievementReached__e(UserId__c = userId, AchievementId__c = achievement.Id)
		};

		// When
		Test.startTest();
		AchievementReachedTriggerHandler handler = new AchievementReachedTriggerHandler(events);
		handler.processEvents();
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> result = [SELECT Id, Key__c, User__c, Achievement__c FROM ReachedAchievement__c];
		Assert.areEqual(1, result.size(), 'No new ReachedAchievement__c are expected to be created');
	}

	@IsTest
	private static void processEvents_multipleEventsWithSameIds_singleRecordCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		List<AchievementReached__e> events = new List<AchievementReached__e> {
			new AchievementReached__e(UserId__c = userId, AchievementId__c = achievement.Id),
			new AchievementReached__e(UserId__c = userId, AchievementId__c = achievement.Id),
			new AchievementReached__e(UserId__c = userId, AchievementId__c = achievement.Id)
		};

		// When
		Test.startTest();
		AchievementReachedTriggerHandler handler = new AchievementReachedTriggerHandler(events);
		handler.processEvents();
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> result = [SELECT Id, Key__c, User__c, Achievement__c FROM ReachedAchievement__c];
		Assert.isNotNull(result, 'ReachedAchievement__c are expected to be created');
		Assert.areEqual(1, result.size(), 'Single ReachedAchievement__c is expected to be created');
		Assert.areEqual(userId, result[0].User__c, 'User__c filed value is expected to match userId');
		Assert.areEqual(achievement.Id, result[0].Achievement__c, 'User__c filed value is expected to match userId');
	}

	@IsTest
	private static void processEvents_invalidUserId_logRecordCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		List<AchievementReached__e> events = new List<AchievementReached__e> {
			new AchievementReached__e(UserId__c = achievement.Id, AchievementId__c = achievement.Id)
		};

		// When
		Test.startTest();
		AchievementReachedTriggerHandler handler = new AchievementReachedTriggerHandler(events);
		handler.processEvents();
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> result = [SELECT Id, Key__c, User__c, Achievement__c FROM ReachedAchievement__c];
		List<Log__c> resultLogs = [SELECT Id FROM Log__c];
		Assert.isTrue(result.isEmpty(), 'No new ReachedAchievement__c are expected to be created');
	}

	@IsTest
	private static void processEvents_invalidAchievementId_logRecordCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		List<AchievementReached__e> events = new List<AchievementReached__e> {
			new AchievementReached__e(UserId__c = userId, AchievementId__c = userId)
		};

		// When
		Test.startTest();
		AchievementReachedTriggerHandler handler = new AchievementReachedTriggerHandler(events);
		handler.processEvents();
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> result = [SELECT Id, Key__c, User__c, Achievement__c FROM ReachedAchievement__c];
		List<Log__c> resultLogs = [SELECT Id FROM Log__c];
		Assert.isTrue(result.isEmpty(), 'No new ReachedAchievement__c are expected to be created');
	}

	@IsTest
	private static void onAfterInsert_201AchievementsReached_recordsCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		List<Achievement__c> achievements = new List<Achievement__c>();
		for (Integer i = 0; i <= 201; i++) {
			achievements.add(TestDataFactory.initAchievement('Achievement' + i, measurement.Id));
		}
		insert achievements;

		List<AchievementReached__e> events = new List<AchievementReached__e>();
		for (Achievement__c achievement : achievements) {
			events.add(new AchievementReached__e(UserId__c = userId, AchievementId__c = achievement.Id));
		}

		// When
		Test.startTest();
		EventBus.publish(events);
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> result = [SELECT Id, Key__c, User__c, Achievement__c FROM ReachedAchievement__c];
		Assert.isNotNull(result, 'ReachedAchievement__c are expected to be created');
		Assert.areEqual(202, result.size(), 'Single ReachedAchievement__c is expected to be created');
	}
}