force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description for the achievement</description>
    <inlineHelpText>Short description used by admin users to better identify list of achievements</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of points that user gets, once reaching the achievement. Used to calculate high-score on the leaderboard</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UIDescription__c.field-meta.xml
<CustomField>
    <fullName>UIDescription__c</fullName>
    <description>Achievement description that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UITitle__c.field-meta.xml
<CustomField>
    <fullName>UITitle__c</fullName>
    <description>Achievement title that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Measurement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AchievementSelector.cls
public with sharing class AchievementSelector extends BaseSelector {

	public static AchievementSelector getInstance() {
		return new AchievementSelector();
	}

	public override SObjectType sObjectType() {
		return Achievement__c.getSobjectType();
	}

	public override Set<SObjectField> queryFields() {
		return new Set<SObjectField> { Achievement__c.Id, Achievement__c.Name, Achievement__c.Description__c, Achievement__c.Goal__c, Achievement__c.Score__c, Achievement__c.UITitle__c, Achievement__c.UIDescription__c, Achievement__c.Measurement__c};
	}
}