force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UserStatSelectorTest.cls
@IsTest
private class UserStatSelectorTest {
	@IsTest
	private static void getByUserIds_recordWithIdExists_recordsReturned(){
		// Given
		Id profileId = UserInfo.getProfileId();

		User user1 = TestDataFactory.createUser(profileId, 'user1');
		User user2 = TestDataFactory.createUser(profileId, 'user2');
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');

		UserStat__c stat1 = TestDataFactory.createUserStat(user1.Id, achievement.Id);
		UserStat__c stat2 = TestDataFactory.createUserStat(user2.Id, achievement.Id);

		// When 
		List<UserStat__c> result = UserStatSelector.getByUserIds(new Set<Id>{ user1.Id });
		Map<Id, UserStat__c> resultMap = new Map<Id, UserStat__c>(result);

		// Then
		System.assertEquals(1, result.size(), 'Record is expected to be found');
		System.assert(resultMap.containsKey(stat1.Id), 'Map is expected to have a specific user stat');
		System.assert(!resultMap.containsKey(stat2.Id), 'Map is not expected to have a specific user stat');
	}

	@IsTest
	private static void getByUserIds_emptyIdsSet_emptyListReturned(){
		// Given
		Set<Id> ids = new Set<Id>();

		// When 
		List<UserStat__c> result = UserStatSelector.getByUserIds(ids);

		// Then
		System.assertNotEquals(null, result, 'Empty list is expected');
		System.assertEquals(0, result.size(), 'Empty list is expected');
	}

	@IsTest
	private static void getByUserIds_noRecordsFound_emptyListReturned(){
		// Given
		Id profileId = UserInfo.getProfileId();
		User user = TestDataFactory.createUser(profileId, 'user');
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');
		UserStat__c stat = TestDataFactory.createUserStat(user.Id, achievement.Id);
		Id userStatId = stat.id;
		delete stat;

		// When 
		List<UserStat__c> result = UserStatSelector.getByUserIds(new Set<Id> { userStatId });

		// Then
		System.assertNotEquals(null, result, 'Empty list is expected');
		System.assertEquals(0, result.size(), 'Empty list is expected');
	}
}