force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AchievementIncrement__e/AchievementIncrement__e.object-meta.xml
<CustomObject>
    <label>Achievement Increment</label>
    <pluralLabel>Achievement Increments</pluralLabel>
</CustomObject>

force-app/main/default/objects/AchievementIncrement__e/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement custom metadata type record name</description>
    <label>Achievement</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AchievementIncrement__e/fields/Increment__c.field-meta.xml
<CustomField>
    <fullName>Increment__c</fullName>
    <description>Value that is going to be added to User Stat - Progress field</description>
    <label>Increment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AchievementIncrement__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>User Id</description>
    <label>UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GameForceLog__c/GameForceLog__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>GameForce Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GameForce Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GameForceLog__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>Related User Id (if applicable)</description>
    <label>User Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs saved by GameForce</description>
    <label>Log</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/AchievementId__c.field-meta.xml
<CustomField>
    <fullName>AchievementId__c</fullName>
    <description>Related Achievement Id (if applicable)</description>
    <label>Achievement Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AchievementIncrementTriggerHandlerTest.cls
@IsTest(isParallel=true)
private class AchievementIncrementTriggerHandlerTest {
	
	@IsTest
	private static void processEvents_singleEventStatsDoesntExist_userStatCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');
		AchievementIncrement__e event = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievement.Id, Increment__c = 1);

		// When
		Test.startTest();
		AchievementIncrementTriggerHandler handler = new AchievementIncrementTriggerHandler(new List<AchievementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<UserStat__c> stats = [SELECT Id, CurrentProgress__c FROM UserStat__c WHERE UserId__c = :userId AND Achievement__c = :achievement.Id];
		system.assertEquals(1, stats.size(), 'Single stat is expected to be created');
		system.assertEquals(1, stats[0].CurrentProgress__c, 'CurrentProgress__c value should be increased for the sum of the increments from the event');
	}

	@IsTest
	private static void processEvents_multipleEventsWithSameIds_userStatCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');
		AchievementIncrement__e event1 = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievement.Id, Increment__c = 1);
		AchievementIncrement__e event2 = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievement.Id, Increment__c = 2);

		// When
		Test.startTest();
		AchievementIncrementTriggerHandler handler = new AchievementIncrementTriggerHandler(new List<AchievementIncrement__e> { event1, event2 });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<UserStat__c> stats = [SELECT Id, CurrentProgress__c FROM UserStat__c WHERE UserId__c = :userId AND Achievement__c = :achievement.Id];
		system.assertEquals(1, stats.size(), 'Single stat is expected to be created');
		system.assertEquals(3, stats[0].CurrentProgress__c, 'CurrentProgress__c value should be increased for the sum of the increments from the event');
	}

	@IsTest
	private static void processEvents_existingUserStat_userStatUpdated() {
		// Given
		Id userId = UserInfo.getUserId();
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');
		UserStat__c stat = TestDataFactory.createUserStat(userId, achievement.Id, 10);

		AchievementIncrement__e event = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievement.Id, Increment__c = 1);

		// When
		Test.startTest();
		AchievementIncrementTriggerHandler handler = new AchievementIncrementTriggerHandler(new List<AchievementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<UserStat__c> stats = [SELECT Id, CurrentProgress__c FROM UserStat__c WHERE UserId__c = :userId AND Achievement__c = :achievement.Id];
		system.assertEquals(1, stats.size(), 'Single stat is expected to be created');
		system.assertEquals(stat.Id, stats[0].Id, 'Existing UserStat__c is expected to be updated');
		system.assertEquals(11, stats[0].CurrentProgress__c, 'CurrentProgress__c value should be increased for the sum of the increments from the event');
	}

	@IsTest
	private static void processEvents_nonExistingAchievementId_logCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');
		String achievementId = achievement.Id;
		delete achievement;
		AchievementIncrement__e event = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievementId, Increment__c = 1);

		// When
		Test.startTest();
		AchievementIncrementTriggerHandler handler = new AchievementIncrementTriggerHandler(new List<AchievementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<GameForceLog__c> logs = [SELECT Id, Log__c, UserId__c, AchievementId__c FROM GameForceLog__c];
		System.assertEquals(1, logs.size(), 'Error Log is expected to be created');
		System.assertEquals(userId, logs[0].UserId__c, 'User Id value is expected to be saved in UserId__c field');
		System.assertEquals(achievementId, logs[0].AchievementId__c, 'Achievement Id value is expected to be saved in AchievementId__c field');
	}

	@IsTest
	private static void processEvents_incrementIsNull_logCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');
		AchievementIncrement__e event = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievement.Id, Increment__c = 0);

		// When
		Test.startTest();
		AchievementIncrementTriggerHandler handler = new AchievementIncrementTriggerHandler(new List<AchievementIncrement__e> { event });
		handler.processEvents();
		Test.stopTest();

		// Then
		List<GameForceLog__c> logs = [SELECT Id, Log__c, UserId__c, AchievementId__c FROM GameForceLog__c];
		System.assertEquals(1, logs.size(), 'Error Log is expected to be created');
		System.assertEquals(userId, logs[0].UserId__c, 'User Id value is expected to be saved in UserId__c field');
		System.assertEquals(achievement.Id, logs[0].AchievementId__c, 'Achievement Id value is expected to be saved in AchievementId__c field');
	}

	@IsTest
	private static void onAfterInsert_eventGetsPublished_userStatCreated() {
		// Given
		Id userId = UserInfo.getUserId();
		Achievement__c achievement = TestDataFactory.createAchievement('achievement');

		// When
		Test.startTest();
		AchievementIncrement__e event = new AchievementIncrement__e(UserId__c = userId, Achievement__c = achievement.Id, Increment__c = 1);
		EventBus.publish(new List<AchievementIncrement__e> { event });
		Test.stopTest();

		// Then
		List<UserStat__c> stats = [SELECT Id, CurrentProgress__c FROM UserStat__c WHERE UserId__c = :userId AND Achievement__c = :achievement.Id];
		system.assertEquals(1, stats.size(), 'Single stat is expected to be created');
		system.assertEquals(1, stats[0].CurrentProgress__c, 'CurrentProgress__c value should be increased for the sum of the increments from the event');
	}

}