force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description for the achievement</description>
    <inlineHelpText>Short description used by admin users to better identify list of achievements</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Disables the achievement and all related logic. Removes achievement from Leaderboards.</description>
    <inlineHelpText>Default value: Checked</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of points that user gets, once reaching the achievement. Used to calculate high-score on the leaderboard</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UIDescription__c.field-meta.xml
<CustomField>
    <fullName>UIDescription__c</fullName>
    <description>Achievement description that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UITitle__c.field-meta.xml
<CustomField>
    <fullName>UITitle__c</fullName>
    <description>Achievement title that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/Reached__c.field-meta.xml
<CustomField>
    <fullName>Reached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true, in case achievement was reached by user</description>
    <label>Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest 
public class TestDataFactory {	
	
	public static Achievement__c initAchievement(String uniqueIdentifier) {
		Achievement__c achievement = new Achievement__c();
		achievement.Name = 'Name ' + uniqueIdentifier;
		achievement.Description__c = 'Generic description ' + uniqueIdentifier;
		achievement.Enabled__c = true;
		achievement.Goal__c = Math.round(1000 * Math.random());
		achievement.Score__c = Math.round(1000 * Math.random());
		achievement.UITitle__c = 'UI Title ' + uniqueIdentifier;
		achievement.UIDescription__c = 'UI Description ' + uniqueIdentifier;
		return  achievement;
	}

	public static Achievement__c createAchievement(String uniqueIdentifier) {
		Achievement__c achievement = TestDataFactory.initAchievement(uniqueIdentifier);
		insert achievement;
		return achievement;
	}

	public static UserStat__c initUserStat(Id userId, Id achievementId) {
		UserStat__c stat = new UserStat__c();
		stat.UserId__c = userId;
		stat.Achievement__c = achievementId;
		stat.CurrentProgress__c = 0;
		stat.Reached__c = false;
		return stat;
	}

	public static UserStat__c initUserStat(Id userId, Id achievementId, Decimal progress) {
		UserStat__c stat = new UserStat__c();
		stat.UserId__c = userId;
		stat.Achievement__c = achievementId;
		stat.CurrentProgress__c = progress;
		stat.Reached__c = false;
		return stat;
	}

	public static UserStat__c createUserStat(Id userId, Id achievementId) {
		UserStat__c stat = TestDataFactory.initUserStat(userId, achievementId);
		insert stat;
		return stat;
	}

	public static UserStat__c createUserStat(Id userId, Id achievementId, Decimal progress) {
		UserStat__c stat = TestDataFactory.initUserStat(userId, achievementId, progress);
		insert stat;
		return stat;
	}

	public static User initUser(Id profileId, String lastName) {
		User user = new User();
		user.ProfileId = profileId;
		user.LastName = lastName;
		user.Email = lastName + '@gameforce.com';
		user.Username = lastName + '@gameforce.com';
		user.Title = lastName + ' title';
		user.Alias = 'alias';
		user.TimeZoneSidKey = 'America/Los_Angeles';
		user.EmailEncodingKey = 'UTF-8';
    	user.LanguageLocaleKey = 'en_US';
		user.LocaleSidKey = 'en_US';

		return user;
	}

	public static User createUser(Id profileId, String lastName) {
		User user = initUser(profileId, lastName);
		insert user;
		return user;
	}
}