force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description for the achievement</description>
    <inlineHelpText>Short description used by admin users to better identify list of achievements</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Disables the achievement and all related logic. Removes achievement from Leaderboards.</description>
    <inlineHelpText>Default value: Checked</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of points that user gets, once reaching the achievement. Used to calculate high-score on the leaderboard</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UIDescription__c.field-meta.xml
<CustomField>
    <fullName>UIDescription__c</fullName>
    <description>Achievement description that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UITitle__c.field-meta.xml
<CustomField>
    <fullName>UITitle__c</fullName>
    <description>Achievement title that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AchievementSelectorTest.cls
@IsTest(isParallel=true)
private class AchievementSelectorTest {
	
	private static Achievement__c generateAchievement(String uniqueIdentifier) {
		Achievement__c achievement = new Achievement__c();
		achievement.Name = 'Name ' + uniqueIdentifier;
		achievement.Description__c = 'Generic description ' + uniqueIdentifier;
		achievement.Enabled__c = true;
		achievement.Goal__c = Math.round(1000 * Math.random());
		achievement.Score__c = Math.round(1000 * Math.random());
		achievement.UITitle__c = 'UI Title ' + uniqueIdentifier;
		achievement.UIDescription__c = 'UI Description ' + uniqueIdentifier;
		return  achievement;
	}

	@IsTest
	private static void getByIds_idMatches_recordReturned(){
		// Given
		Achievement__c achievement1 = generateAchievement('OK1');
		Achievement__c achievement2 = generateAchievement('OK2');
		Achievement__c achievement3 = generateAchievement('NOTOK1');
		insert new List<Achievement__c> { achievement1, achievement2, achievement3 };
		Set<Id> ids = new Set<Id>{achievement1.id, achievement2.Id};

		// When 
		List<Achievement__c> result = AchievementSelector.getByIds(ids);

		// Then
		system.assertEquals(2, result.size(), '2 records are expected to be found');
		Map<Id, Achievement__c> resultMap = new Map<Id, Achievement__c>(result);
		system.assert(resultMap.containsKey(achievement1.Id), 'First achievement is expected to be found');
		system.assert(resultMap.containsKey(achievement2.Id), 'Second achievement is expected to be found');
		system.assert(!resultMap.containsKey(achievement3.Id), 'Third achievement is expected not to be found');
	}

	@IsTest
	private static void getByIds_emptyListOfIds_emptyListReturned(){
		// Given
		Set<Id> ids = new Set<Id>();

		// When 
		List<Achievement__c> result = AchievementSelector.getByIds(ids);

		// Then
		system.assertNotEquals(null, result, 'Empty list is expected instead of null');
		system.assertEquals(0, result.size(), 'Empty list is expected');
	}

	@IsTest
	private static void getByIds_noRecordsFound_emptyListReturned(){
		// Given
		Achievement__c achievement1 = generateAchievement('EXISTS1');
		Achievement__c achievement2 = generateAchievement('EXISTS2');
		Achievement__c achievement3 = generateAchievement('REMOVED');
		insert new List<Achievement__c> { achievement1, achievement2, achievement3 };
		Set<Id> ids = new Set<Id>{ achievement3.id };
		delete new List<Achievement__c> { achievement3 };

		// When 
		List<Achievement__c> result = AchievementSelector.getByIds(ids);

		// Then
		system.assertNotEquals(null, result, 'Empty list is expected instead of null');
		system.assertEquals(0, result.size(), 'Empty list is expected');
	}
}