force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/UIDescription__c.field-meta.xml
<CustomField>
    <fullName>UIDescription__c</fullName>
    <description>Achievement description that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/UITitle__c.field-meta.xml
<CustomField>
    <fullName>UITitle__c</fullName>
    <description>Achievement title that is going to be shown in the UI elements</description>
    <inlineHelpText>Supports plain text, as well as reference to the Custom Labels API Name</inlineHelpText>
    <label>UI Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AchievementsDataHelper.cls
public with sharing class AchievementsDataHelper {
	public static Map<Id, List<DataWrappers.AchievementCardData>> getAchievementsDataPerUserId(Set<Id> userIds) {
		Map<Id, List<DataWrappers.AchievementCardData>> result = new Map<Id, List<DataWrappers.AchievementCardData>>();
		List<Achievement__c> allAchievements = AchievementSelector.getInstance().getAll();
		Map<Id, Set<Id>> reachedAchievementIdsByUserId = new Map<Id, Set<Id>>();
		List<ReachedAchievement__c> reachedAchievements = ReachedAchievementSelector.getInstance().getByFieldValue('User__c', 'IN', userIds);
		for (ReachedAchievement__c reachedAchievement : reachedAchievements) {
			if (!reachedAchievementIdsByUserId.containsKey(reachedAchievement.User__c)) {
				reachedAchievementIdsByUserId.put(reachedAchievement.User__c, new Set<Id>());
			} 
			reachedAchievementIdsByUserId.get(reachedAchievement.User__c).add(reachedAchievement.Achievement__c);
		}

		for (Id userId : userIds) {
			if (!result.containsKey(userId)) {
				result.put(userId, new List<DataWrappers.AchievementCardData>());
			}
			List<DataWrappers.AchievementCardData> userAchievements = result.get(userId);

			for (Achievement__c achievement : allAchievements) {
				Boolean isReached = reachedAchievementIdsByUserId.containsKey(userId) && reachedAchievementIdsByUserId.get(userId).contains(achievement.Id);
				DataWrappers.AchievementCardData achievementCardData = initAchievementCardData(achievement, isReached);
				userAchievements.add(achievementCardData);
			}
		}

		return result;
	}

	public static DataWrappers.AchievementCardData initAchievementCardData(Achievement__c achievement, Boolean isReached) {
		DataWrappers.AchievementCardData achievementWrapper = new DataWrappers.AchievementCardData();
		achievementWrapper.id = achievement.Id;
		achievementWrapper.uiTitle = achievement.UITitle__c;
		achievementWrapper.uiDescription = achievement.UIDescription__c;
		achievementWrapper.isReached = isReached;
		return achievementWrapper;
	}
}