force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AchievementsListControllerTest.cls
@IsTest
private class AchievementsListControllerTest {
    @IsTest 
	private static void getCurrentUserAchievementsList_ReachedAchievementExists_AchievementListReturned() {
        // Given
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement1 = TestDataFactory.initAchievement('Ach1', measurement.Id);
		Achievement__c achievement2 = TestDataFactory.initAchievement('Ach2', measurement.Id);
		insert new List<Achievement__c> { achievement1, achievement2 };

		ReachedAchievement__c reachedAchievement = TestDataFactory.createReachedAchievement(UserInfo.getUserId(), achievement1.Id);

		// When
		Test.startTest();
        Map<String, Object> result = AchievementsListController.getCurrentUserAchievementsList();
		Test.stopTest();

		// Then
        System.assert(result.containsKey('Success'), 'Resulting map is expected to have "Success" key');
        System.assert(!result.containsKey('Warning'), 'Resulting map is not expected to have "Warning" key');
        System.assert(!result.containsKey('Error'), 'Resulting map is not expected to have "Error" key');

        List<DataWrappers.AchievementCardData> userAchievementCardDataList = (List<DataWrappers.AchievementCardData>) result.get('Success');
        System.assertEquals(2, userAchievementCardDataList.size(), '2 Achievements are expected');
		for (DataWrappers.AchievementCardData achievementData : userAchievementCardDataList) {
			if (achievementData.id == achievement1.Id) {
				System.assertEquals(true, achievementData.isReached, 'First achievement for the user is expected to be marked as reached');
			} else {
				System.assertEquals(false, achievementData.isReached, 'All other achievements are expected to be not reached');
			}
		}
    }
}