force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/Reached__c.field-meta.xml
<CustomField>
    <fullName>Reached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true, in case achievement was reached by user</description>
    <label>Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserStatSelector.cls
public with sharing class UserStatSelector {
	private static final String FIELDS_LIST = 'Id, Name, Achievement__c, CurrentProgress__c, Reached__c, UserId__c';

	public static List<UserStat__c> getByUserIds(Set<Id> userIds) {
		if (userIds.isEmpty()) {
			return new List<UserStat__c>();
		}

		Map<String, Object> binds = new Map<String, Object> { 'userIds' => userIds };
		return Database.queryWithBinds('SELECT ' + FIELDS_LIST + ' FROM UserStat__c WHERE UserId__c IN :userIds', binds, System.AccessLevel.SYSTEM_MODE);
	}
}