force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of points that user gets, once reaching the achievement. Used to calculate high-score on the leaderboard</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Achievement__r.Score__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeaderboardControllerTest.cls
@IsTest
private class LeaderboardControllerTest {

	@IsTest
	private static void getTotalNumberOfAchievements_achievementExists_countReturned() {
		// Given
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement1 = TestDataFactory.createAchievement('Ach1', measurement.Id);
		Achievement__c achievement2 = TestDataFactory.createAchievement('Ach2', measurement.Id);
		Achievement__c achievement3 = TestDataFactory.createAchievement('Ach3', measurement.Id);

		// When 
		Test.startTest();
		Map<String, Object> result = LeaderboardController.getTotalNumberOfAchievements();
		Test.stopTest();

		// Then
		System.assert(result.containsKey('Success'), 'Map is expected to contain Success key');
		System.assert(!result.containsKey('Error'), 'Map is expected to contain Error key');
		System.assert(!result.containsKey('Warning'), 'Map is expected to contain Warning key');
		System.assertEquals(3, (Decimal) result.get('Success'), ' 3 records are expected to be returned');
	}

	@IsTest
	private static void getUserInfoById_userWithReachedAchivementsExists_infoReturned() {
		// Given
		User usr = [SELECT Id, Name, FullPhotoUrl FROM User WHERE ID = :UserInfo.getUserId() LIMIT 1];
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement1 = TestDataFactory.createAchievement('Ach1', measurement.Id);
		Achievement__c achievement2 = TestDataFactory.createAchievement('Ach2', measurement.Id);
		ReachedAchievement__c reachedAchievement1 = TestDataFactory.createReachedAchievement(usr.Id, achievement1.Id);
		ReachedAchievement__c reachedAchievement2 = TestDataFactory.createReachedAchievement(usr.Id, achievement2.Id);

		// When 
		Test.startTest();
		Map<String, Object> result = LeaderboardController.getCurrentUserInfo();
		Test.stopTest();

		// Then
		System.assert(result.containsKey('Success'), 'Map is expected to contain Success key');
		System.assert(!result.containsKey('Error'), 'Map is expected to contain Error key');
		System.assert(!result.containsKey('Warning'), 'Map is expected to contain Warning key');
		LeaderboardController.UserInfoWrapper userInfoWrapper = (LeaderboardController.UserInfoWrapper) result.get('Success');
		System.assertEquals(usr.Name, userInfoWrapper.name, 'Name of current user is expected to be returned');
		System.assertEquals(usr.FullPhotoUrl, userInfoWrapper.fullPhotoUrl, 'FullPhotoUrl of current user is expected to be returned');
		System.assertEquals(2, userInfoWrapper.numberOfAchievements, 'Total number of achievements is expected');
		System.assertEquals(achievement1.Score__c + achievement2.Score__c, userInfoWrapper.totalScore, 'Total score of all reached achievements is expected');
	}
}