force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UserStatTriggerTest.cls
@IsTest(isParallel=true)
private class UserStatTriggerTest {

	private static List<Achievement__c> createAchievements(Integer numberOfAchivements) {
		List<Achievement__c> achievements = new List<Achievement__c>();
		for (Integer i = 0; i < numberOfAchivements; i++) {
			Achievement__c achievement = TestDataFactory.initAchievement(String.valueOf(i));
			achievement.Goal__c = 5;
			achievements.add(achievement);
		}
		insert achievements;
		return achievements;
	}

	private static List<UserStat__c> initUserStats(List<Achievement__c> achievements, Integer currentProgress) {
		Id userId = UserInfo.getUserId();
		List<UserStat__c> stats = new List<UserStat__c>();
		for (Achievement__c achievement : achievements) {
			UserStat__c stat = TestDataFactory.initUserStat(userId, achievement.Id);
			stat.CurrentProgress__c = currentProgress;
			stats.add(stat);
		}

		return stats;
	}

	@IsTest
	private static void onAfterInsert_201RecordsInserted_noException() {
		// Given
		List<Achievement__c> achievements = createAchievements(201);
		List<UserStat__c> stats = initUserStats(achievements, 20);

		// When
		Test.startTest();
		insert stats;
		Test.stopTest();

		// Then
		system.assert(true, 'No exception is expected when inserting running more then 200 records');
	}

	@IsTest
	private static void onAfterUpdate_201RecordsUpdated_noException() {
		// Given
		List<Achievement__c> achievements = createAchievements(201);
		List<UserStat__c> stats = initUserStats(achievements, 0);
		insert stats;

		// When
		Test.startTest();
		for (UserStat__c stat : stats) {
			stat.CurrentProgress__c = 20;
		}
		update stats;
		Test.stopTest();

		// Then
		system.assert(true, 'No exception is expected when inserting running more then 200 records');
	}
}