force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeasonReachedAchievement__c/SeasonReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Season Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Season Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Season Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Season Reached Achievements</relationshipLabel>
    <relationshipName>SeasonReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeasonReachedAchievement__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>SeasonReachedAchievements</relationshipLabel>
    <relationshipName>SeasonReachedAchievements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeasonReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SeasonReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SeasonReachedAchievementsBatch.cls
public with sharing class SeasonReachedAchievementsBatch implements Database.Batchable<sObject>, Database.Stateful {
	public Id currentSeasonId;

	public SeasonReachedAchievementsBatch(Id seasonId) {
		if (seasonId == null || seasonId.getSobjectType() != Season__c.getSobjectType()) {
			throw new SeasonReachedAchievementsBatchException('Unable to execute SeasonReachedAchievementsBatch. Provided season id is either null or is not of Season__c type'); 
		}

		currentSeasonId = seasonId;
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		String queryString = 'SELECT Id, Achievement__c, User__c FROM ReachedAchievement__c';
		return Database.getQueryLocator(queryString);
	}

	public void execute(Database.BatchableContext bc, List<sObject> scope) {

		List<SeasonReachedAchievement__c> seasonReachedAchievementsToCreate = new List<SeasonReachedAchievement__c>();

		for (ReachedAchievement__c reachedAchievement : (List<ReachedAchievement__c>)scope) {
			SeasonReachedAchievement__c seasonReachedAchievement = new SeasonReachedAchievement__c();
			seasonReachedAchievement.Season__c = currentSeasonId;
			seasonReachedAchievement.User__c = reachedAchievement.User__c;
			seasonReachedAchievement.Achievement__c = reachedAchievement.Achievement__c;

			seasonReachedAchievementsToCreate.add(seasonReachedAchievement);
		}
		insert seasonReachedAchievementsToCreate;
		delete scope;
	}

	public void finish(Database.BatchableContext bc) {
		// if (isSeasonMissing) {
		// 	Logger.saveSingleLog('Unable to execute SeasonUserStatsBatch - current season is missing.');
		// }
	}

	public class SeasonReachedAchievementsBatchException extends Exception {}
}