force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AchievementReached__e/AchievementReached__e.object-meta.xml
<CustomObject>
    <description>Fired when user has reached the achievement</description>
    <label>Achievement Reached</label>
    <pluralLabel>Achievements Reached</pluralLabel>
</CustomObject>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/Reached__c.field-meta.xml
<CustomField>
    <fullName>Reached__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true, in case achievement was reached by user</description>
    <label>Reached</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserStatsTriggerHandler.cls
public with sharing class UserStatsTriggerHandler {
	public static void onBeforeInsert(Map<Id, sObject> newMap) {

	}

	public static void onBeforeUpdate(Map<Id, sObject> newMap, Map<Id, sObject> oldMap) {
		List<AchievementReached__e> achievementsReached = new List<AchievementReached__e>();
		
		Set<Id> achievementIds = new Set<Id>();
		List<UserStat__c> changedStats = new List<UserStat__c>();
		for (Id statId : newMap.keySet()) {
			UserStat__c statNew = (UserStat__c) newMap.get(statId);
			UserStat__c statOld = (UserStat__c) newMap.get(statId);

			if (statNew.CurrentProgress__c > statOld.CurrentProgress__c) {
				changedStats.add(statNew);
				achievementIds.add(changedStats.Achievement__c);
			}
		}

		if (achievementIds.isEmpty() || changedStats.isEmpty()) {
			return;
		}

		List<Achievement__c> achievements = AchievementSelector.getByIds(achievementIds);
		if (achievements.isEmpty()) {
			return;
		}

		Map<Id, Achievement__c> achievementsMap = new Map<Id, Achievement__c> (achievements);

		for (UserStat__c stat : changedStats) {
			Achievement__c achievement = achievementsMap.get(stat.Achievement__c);
			if (stat.CurrentProgress__c >= achievement.Goal__c && !stat.Reached__c) {
				stat.Reached__c = true;

				// System to format Payload split it into valid JSONs of 131072 length and pack them in 
				// AchievementReached__e event
			}
		}

		if (!achievementsReached.isEmpty()) {
			// Call method to publish events
			List<Database.SaveResult> results = EventBus.publish(inkEvents);

			// Inspect publishing result for each event
			for (Database.SaveResult sr : results) {
				if (sr.isSuccess()) {
					System.debug('Successfully published event.');
				} else {
					for(Database.Error err : sr.getErrors()) {
						System.debug('Error returned: ' +
									err.getStatusCode() +
									' - ' +
									err.getMessage());
					}
				}  
			}
		}
	}
}