force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserStatMapper.cls
public with sharing class UserStatMapper {

	Map<Id, Map<Id, UserStat__c>> userStatByAchievementIdAndUserIdMap = new Map<Id, Map<Id, UserStat__c>>();
	
	public UserStatMapper(List<UserStat__c> stats) {
		initMap(stats);
	}

	private void initMap(List<UserStat__c> stats) {
		for (UserStat__c stat : stats) {
			if (!userStatByAchievementIdAndUserIdMap.containsKey(stat.UserId__c)) {
				userStatByAchievementIdAndUserIdMap.put(stat.UserId__c, new Map<Id, UserStat__c>());
			}

			userStatByAchievementIdAndUserIdMap.get(stat.UserId__c).put(stat.Achievement__c, stat);
		}
	}

	public UserStat__c findByUserIdAndAchievementId(Id userId, Id achievementId) {
		return userStatByAchievementIdAndUserIdMap.get(userId)?.get(achievementId);
	}
}