force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AchievementIncrement__e/AchievementIncrement__e.object-meta.xml
<CustomObject>
    <label>Achievement Increment</label>
    <pluralLabel>Achievement Increments</pluralLabel>
</CustomObject>

force-app/main/default/objects/AchievementIncrement__e/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement custom metadata type record name</description>
    <label>Achievement</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AchievementIncrement__e/fields/Increment__c.field-meta.xml
<CustomField>
    <fullName>Increment__c</fullName>
    <description>Value that is going to be added to User Stat - Progress field</description>
    <label>Increment</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AchievementIncrement__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>User Id</description>
    <label>UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserStats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AchievementIncrementHandler.cls
public with sharing class AchievementIncrementHandler {

	public static void onAfterInsert(List<AchievementIncrement__e> events) {
		// SPLIT THIS SPAGHETTI
		List<UserStat__c> statsToInsert = new List<UserStat__c>();
		Map<Id, UserStat__c> statsToUpdate = new Map<Id, UserStat__c>();
		
		Set<Id> userIds = new Set<Id>();
		Set<Id> achievementIds = new Set<Id>();
		for (AchievementIncrement__e event : events) {
			userIds.add(event.UserId__c);
			achievementIds.add(event.Achievement__c);
		}

		// CHANGE TO USER SELECTOR
		Map<Id, User> usersMap = new Map<Id, User> ([SELECT ID FROM User WHERE Id IN :userIds]);
		Map<Id, Achievement__c> achievementsMap = new Map<Id, Achievement__c> (AchievementSelector.getByIds(achievementIds));

		List<UserStat__c> existingStats = UserStatSelector.getByUserIds(userIds);
		UserStatMapper existingStatsMapper = new UserStatMapper(existingStats);

		for (AchievementIncrement__e event : events) {
			User user = usersMap.get(event.UserId__c);
			Achievement__c achievement = achievementsMap.get(event.Achievement__c);

			if (user == null || achievement == null) {
				continue;
			}

			UserStat__c existingStat = existingStatsMapper.findByUserIdAndachievementId(event.UserId__c, event.Achievement__c);
			if (existingStat != null) {
				if (!statsToUpdate.containsKey(existingStat.Id)) {
					statsToUpdate.put(existingStat.Id, existingStat);
				}

				statsToUpdate.get(existingStat.Id).CurrentProgress__c += event.Increment__c;
			} else {
				statsToInsert.add(new UserStat__c(Achievement__c = event.Achievement__c, UserId__c = event.UserId__c, CurrentProgress__c = event.Increment__c));
			}
		}

		statsToInsert.addAll(statsToUpdate.values());
		if (!statsToInsert.isEmpty()) {
			// Use proper Database class operations
			upsert statsToInsert;
		}
	}
}