force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Numerical value representing a goal number that has to be reached for achievement to be tracked as &quot;Reached&quot; by the user</description>
    <label>Goal</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UserStat__c/UserStat__c.object-meta.xml
<CustomObject>
    <description>Stores data about current progress of the user</description>
    <label>User Stat</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserStat__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <description>Achievement reference</description>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>User Stats</relationshipLabel>
    <relationshipName>UserStats</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/UserStat__c/fields/CurrentProgress__c.field-meta.xml
<CustomField>
    <fullName>CurrentProgress__c</fullName>
    <label>Current Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AchievementReachedEventsManagerTest.cls
@IsTest(isParallel=true)
private class AchievementReachedEventsManagerTest {

	@IsTest
	private static void fireEventNumberOfEventsTest() {
		// Given
		Achievement__c achievement = TestDataFactory.initAchievement('01');
		insert achievement;

		UserStat__c stat = TestDataFactory.initUserStat(UserInfo.getUserId(), achievement.Id);
		insert stat;
		stat.CurrentProgress__c = achievement.Goal__c + 1;

		Map<Id, UserStat__c> userStatByIdMap = new Map<Id, UserStat__c> {stat.Id => stat};

		// When
		Test.startTest();
		AchievementReachedEventsManager eventsManager = new AchievementReachedEventsManager(userStatByIdMap);
		List<Database.SaveResult> results = eventsManager.fireEvents();
		Test.stopTest();

		// Then
		System.assertNotEquals(null, results, 'Results are expected to be returned by the method');
		System.assertEquals(1, results.size(), 'Single event is expected to be sent per 1 stat');
		for (Database.SaveResult result : results) {
			System.assert(result.isSuccess(), 'Event is expected to be sent without any issues');
		}
	}

	@IsTest
	private static void fireEventEmptyMapValidationTest() {
		// Given
		Map<Id, UserStat__c> userStatByIdMap = new Map<Id, UserStat__c>();

		// When
		Test.startTest();
		AchievementReachedEventsManager eventsManager = new AchievementReachedEventsManager(userStatByIdMap);
		List<Database.SaveResult> results = eventsManager.fireEvents();
		Test.stopTest();

		// Then
		System.assertEquals(null, results, 'Validation is expected to prevent any Events from being sent');
	}
}