force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>The list of achievement that users can get</description>
    <label>Achievement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Measurement__c.field-meta.xml
<CustomField>
    <fullName>Measurement__c</fullName>
    <label>Measurement</label>
    <referenceTo>Measurement__c</referenceTo>
    <relationshipLabel>Achievements</relationshipLabel>
    <relationshipName>Achievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Measurement__c/Measurement__c.object-meta.xml
<CustomObject>
    <description>A list of system-wide statistics that are being counted towards the goals defined in Achievement sObject. (For example: number of converted lead)</description>
    <label>Measurement</label>
    <nameField>
        <displayFormat>M{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Measurements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/ReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Reached Achievements</relationshipLabel>
    <relationshipName>ReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeasonReachedAchievement__c/SeasonReachedAchievement__c.object-meta.xml
<CustomObject>
    <label>Season Reached Achievement</label>
    <nameField>
        <displayFormat>RA{0000000}</displayFormat>
        <label>Season Reached Achievement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Season Reached Achievements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeasonReachedAchievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <referenceTo>Achievement__c</referenceTo>
    <relationshipLabel>Season Reached Achievements</relationshipLabel>
    <relationshipName>SeasonReachedAchievements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeasonReachedAchievement__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Season</label>
    <referenceTo>Season__c</referenceTo>
    <relationshipLabel>SeasonReachedAchievements</relationshipLabel>
    <relationshipName>SeasonReachedAchievements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeasonReachedAchievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SeasonReachedAchievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SeasonReachedAchievementsBatchTest.cls
@IsTest(isParallel=false)
private class SeasonReachedAchievementsBatchTest {
	@IsTest
	private static void execute_allDataExists_reachedAchievementsStored() {
		// Given 
		User userWithAchievement = TestDataFactory.createUser(UserInfo.getProfileId(), 'Test_SidebarApps');
		Season__c currentSeason = TestDataFactory.createSeason(Date.today().addDays(-3), Date.today());

		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		Achievement__c achievement = TestDataFactory.createAchievement('Achievement', measurement.Id);
		ReachedAchievement__c reachedAchievement = TestDataFactory.createReachedAchievement(userWithAchievement.Id, achievement.Id);

		// When 
		Test.startTest();
		Database.executeBatch(new SeasonReachedAchievementsBatch(currentSeason.Id), 200);
		Test.stopTest();

		// Then
		List<ReachedAchievement__c> reachedAchievements = [SELECT Id FROM ReachedAchievement__c];
		Assert.isTrue(reachedAchievements.isEmpty(), 'ReachedAchievement__c sObject records are supposed to be cleaned-up');

		List<SeasonReachedAchievement__c> seasonReachedAchievements = [SELECT Id, User__c, Season__c, Achievement__c FROM SeasonReachedAchievement__c];
		Assert.areEqual(1, seasonReachedAchievements.size(), 'Each ReachedAchievement__c is expected to be migrated');

		SeasonReachedAchievement__c seasonReachedAchievement = seasonReachedAchievements[0];
		Assert.areEqual(currentSeason.Id, seasonReachedAchievement.Season__c, 'Season is expected to be set');
		Assert.areEqual(userWithAchievement.Id, seasonReachedAchievement.User__c, 'User Id is expected to be migrated');
		Assert.areEqual(achievement.Id, seasonReachedAchievement.Achievement__c, 'Achievement Id is expected to be migrated');
	}

	@IsTest
	private static void execute_200reachedAchievements_200reachedAchievementsStored() {
		// Given 
		User userWithAchievement = TestDataFactory.createUser(UserInfo.getProfileId(), 'Test_SidebarApps');
		Season__c currentSeason = TestDataFactory.createSeason(Date.today().addDays(-3), Date.today());

		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');
		
		List<Achievement__c> testAchievements = new List<Achievement__c>();
		for (Integer i = 0; i < 200; i++) {
			testAchievements.add(TestDataFactory.initAchievement('Achievement' + String.valueOf(i), measurement.Id));
		}
		insert testAchievements;
		testAchievements = [SELECT Id FROM Achievement__c];

		List<ReachedAchievement__c> reachedAchievements = new List<ReachedAchievement__c>();
		for (Achievement__c achievement : testAchievements) {
			reachedAchievements.add(TestDataFactory.initReachedAchievement(userWithAchievement.Id, achievement.Id));
		}
		insert reachedAchievements;

		// When 
		Test.startTest();
		Database.executeBatch(new SeasonReachedAchievementsBatch(currentSeason.Id), 200);
		Test.stopTest();

		// Then
		reachedAchievements = [SELECT Id FROM ReachedAchievement__c];
		Assert.isTrue(reachedAchievements.isEmpty(), 'ReachedAchievement__c sObject records are supposed to be cleaned-up');

		List<SeasonReachedAchievement__c> seasonReachedAchievements = [SELECT Id, User__c, Achievement__c FROM SeasonReachedAchievement__c];
		Assert.areEqual(200, seasonReachedAchievements.size(), 'Each ReachedAchievement__c is expected to be migrated');
	}

	@IsTest
	private static void execute_seasonIdIsWrong_exceptionIsThrown() {
		// Given 
		Measurement__c measurement = TestDataFactory.createMeasurement('Measurement');

		// When 
		try { 
			Test.startTest();
			Database.executeBatch(new SeasonReachedAchievementsBatch(measurement.Id), 200);
			Test.stopTest();

			Assert.fail('Exception is expected to be thrown');
		} catch (SeasonReachedAchievementsBatch.SeasonReachedAchievementsBatchException e) {
			String msg = 'Unable to execute SeasonReachedAchievementsBatch. Provided season id is either null or is not of Season__c type';
			Assert.areEqual(msg, e.getMessage(), 'SeasonReachedAchievementsBatchException exception is expected');
		} catch (Exception e) {
			Assert.fail('Exception of SeasonReachedAchievementsBatchException is expected');
		}
		
	}
}